### ISSUE TITLE
.NET Core 3.0 Desktop API Analyzer resize issue

### ISSUE THREAD

**Issue by GeertvanHorrik** [microsoft/dotnet-apiport-ui#2]
See original ticket at https://github.com/Microsoft/dotnet-apiport/issues/698

![image](https://user-images.githubusercontent.com/1246444/43920922-906bd95c-9c1a-11e8-909b-0b9090c3b60e.png)

**Comment by RussKie** [comment]
Looks like the release is built from a different commit, as the latest commit b38695a4299f1df1a95c8e7a4fa479cbd494dad1 doesn't have the problem:
![image](https://user-images.githubusercontent.com/4403806/51372674-0e23b480-1b52-11e9-8127-8de3e05f49b4.png)

**Comment by RussKie** [comment]
Looks like the release is built from a different commit, as the latest commit b38695a4299f1df1a95c8e7a4fa479cbd494dad1 doesn't have the problem:
![api-analyser-resize](https://user-images.githubusercontent.com/4403806/51372709-2b588300-1b52-11e9-8c09-5b62a77a0ed9.gif)

**Comment by terrajobst** [comment]
API Port has been deprecated in favor of Upgrade Assistant (https://github.com/dotnet/upgrade-assistant).
