### ISSUE TITLE
Unable to analyzer app in .NET Core 3.0 Desktop API Analyzer

### ISSUE THREAD

**Issue by GeertvanHorrik** [microsoft/dotnet-apiport-ui#3]
See original ticket here:

https://github.com/Microsoft/dotnet-apiport/issues/697

```
Unable to analyze.
Details:
Detecting assembly references                      [Failed]

Cannot locate assembly information for System.Object. Microsoft assemblies found are:


Cannot locate assembly information for System.Object. Microsoft assemblies found are:


Cannot locate assembly information for System.Object. Microsoft assemblies found are:


Cannot locate assembly information for System.Object. Microsoft assemblies found are:
```

As @chucker found out, this is related to resource assemblies (so means most apps aren't using them if this is tested against lots of LoB apps?).

**Comment by mte3bikri** [comment]
Like all Microsoft analyzer or Helper tools. Very poor tool and never works for the first time, we have, always, to look after and debug to make it work properly.

**Comment by tstephansen** [comment]
I'm having the same issue.

**Comment by RussKie** [comment]
Same here, trying to analyse a [build from GitExtensions](https://ci.appveyor.com/api/buildjobs/ktj0mm5rpkw2q5n5/artifacts/GitExtensions-Portable-3.0.1.4901.zip) and the analyser fails...

**Comment by RussKie** [comment]
After deleting all `*.resources.dll` I managed to get it to work. 
Thanks for the hint @GeertvanHorrik and  @chucker.

**Comment by terrajobst** [comment]
API Port has been deprecated in favor of Upgrade Assistant (https://github.com/dotnet/upgrade-assistant).
