### ISSUE TITLE
Recreate UI in WPF

### ISSUE THREAD

**Issue by deanchalk** [microsoft/dotnet-apiport-ui#5]
The WinForms UI for this app is not a great experience. 
As an experienced WinForms and WPF developer, I'd be happy to recreate it in WPF for a better user experience.
If this is OK, ill do this and submit a PR

**Comment by terrajobst** [comment]
API Port has been deprecated in favor of Upgrade Assistant (https://github.com/dotnet/upgrade-assistant).
